version: '3.5'
services:
    mysql-master:
        image: mysql:5.7
        container_name: mysql_master
        environment:
            MYSQL_DATABASE: demo
            MYSQL_ROOT_PASSWORD: "123456"
        restart: on-failure
        volumes:
            - ./mysql/master:/var/lib/mysql
        ports:
            - 3307:3306

    eureka-master:
        build: ./eureka-point
        container_name: eureka-master
        restart: on-failure
        ports:
            - 8100:8080
        environment:
            - REGISTER_WITH_EUREKA=false
            - FETCH_REGISTER=false
            - SECURITY_NAME=admin
            - SECURITY_PASSWORD=123456
            - DEFAULT_ZONE=http://admin:123456@eureka-slave-one:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - HOSTNAME=eureka-master
    eureka-slave-one:
        build: ./eureka-point
        container_name: eureka-slave-one
        restart: on-failure
        ports: 
            - 8101:8080
        environment:
            - REGISTER_WITH_EUREKA=false
            - FETCH_REGISTER=false
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - HOSTNAME=eureka-slave-one
        depends_on: 
            - eureka-master
    eureka-slave-two:
        build: ./eureka-point
        container_name: eureka-slave-two
        restart: on-failure
        ports: 
            - 8102:8080
        environment:
            - REGISTER_WITH_EUREKA=false
            - FETCH_REGISTER=false
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-one:8080/eureka/
            - HOSTNAME=eureka-slave-two
        depends_on: 
            - eureka-master
