version: '3.5'
services:
    mysql-master:
        image: mysql:5.7
        container_name: mysql_master
        environment:
            MYSQL_DATABASE: demo
            MYSQL_ROOT_PASSWORD: "123456"
        restart: on-failure
        volumes:
            - ./mysql/master:/var/lib/mysql
        ports:
            - 3307:3306

    eureka-master:
        build: ./eureka-point
        container_name: eureka-master
        restart: on-failure
        ports:
            - 8100:8080
        environment:
            - REGISTER_WITH_EUREKA=false
            - FETCH_REGISTER=false
            - SECURITY_NAME=admin
            - SECURITY_PASSWORD=123456
            - DEFAULT_ZONE=http://admin:123456@eureka-slave-one:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - HOSTNAME=eureka-master
    eureka-slave-one:
        build: ./eureka-point
        container_name: eureka-slave-one
        restart: on-failure
        ports: 
            - 8101:8080
        environment:
            - REGISTER_WITH_EUREKA=false
            - FETCH_REGISTER=false
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - HOSTNAME=eureka-slave-one
        depends_on: 
            - eureka-master
    eureka-slave-two:
        build: ./eureka-point
        container_name: eureka-slave-two
        restart: on-failure
        ports: 
            - 8102:8080
        environment:
            - REGISTER_WITH_EUREKA=false
            - FETCH_REGISTER=false
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-one:8080/eureka/
            - HOSTNAME=eureka-slave-two
        depends_on: 
            - eureka-master
    admin-server-point:
        build: ./admin-server-point
        container_name: admin-server-point
        restart: on-failure
        ports: 
            - 8103:8080
        environment:
            - HOSTNAME=admin-server-point 
            - SECURITY_NAME=admin
            - SECURITY_PASSWORD=123456
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-one:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - ACTIVE=prod
        depends_on: 
            - eureka-master

    authenticate-service-point:
        build: ./authenticate-service
        container_name: authenticate-service 
        restart: on-failure
        ports:
            - 8104:8080
        environment: 
            - HOSTNAME=authenticate-service-point 
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-one:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - ACTIVE=prod

    core-service-point:
        build: ./core-service
        container_name: core-service 
        restart: on-failure
        ports:
            - 8105:8080
        environment: 
            - HOSTNAME=core-service-point 
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-one:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - ACTIVE=prod

    message-service-point:
        build: ./message-service
        container_name: message-service 
        restart: on-failure
        ports:
            - 8106:8080
        environment: 
            - HOSTNAME=message-service-point 
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-one:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - ACTIVE=prod

    resource-service-point:
        build: ./resource-service
        container_name: resource-service 
        restart: on-failure
        ports:
            - 8107:8080
        environment: 
            - HOSTNAME=resource-service-point 
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-one:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - ACTIVE=prod
        volumes:
            - ./images:/project/images

    gateway-service-point:
        build: ./gateway-point
        container_name: gateway-service 
        restart: on-failure
        ports:
            - 8108:8080
        environment: 
            - HOSTNAME=gateway-service-point 
            - DEFAULT_ZONE=http://admin:123456@eureka-master:8080/eureka/,http://admin:123456@eureka-slave-one:8080/eureka/,http://admin:123456@eureka-slave-two:8080/eureka/
            - ACTIVE=prod

    chat-ui:
        build: ./chat-ui
        container_name: chat-service
        restart: on-failure
        ports: 
            - 8109:80

    admin-ui:
        build: ./admin-ui
        container_name: admin-service
        restart: on-failure
        ports: 
            - 8110:80
