server:
  port: 8080

spring:
  application:
    name: gateway-point

  cloud:
    gateway:
      routes:

      - predicates:
        - Path=/ws/**
        filters:
          - StripPrefix=1
        uri: http://message-service

      - predicates:
        - Path=/api/**
        filters:
          - StripPrefix=1
        uri: http://authenticate-service

      - predicates:
        - Path=/core-api/**
        filters:
          - StripPrefix=1
        uri: http://core-service

      - predicates:
        - Path=/resource-api/**
        filters:
          - StripPrefix=1
        uri: http://resource-service

      - predicates:
        - Path=/auth/**
        filters:
          - StripPrefix=1
        uri: http://authenticate-service

      - predicates:
        - Path=/message-api/**
        filters:
          - StripPrefix=1
        uri: http://message-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
